[project]
name = "wilton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mako>=1.3.12",
    "markdown-it-py[plugins]>=4.2.0",
    "pagefind[bin]>=1.5.2",
    "pydantic>=2.13.4",
    "python-frontmatter>=1.3.0",
    "sqlmodel>=0.0.38",
    "toml>=0.10.2",
]
