[project]
name = "wilton"
version = "0.1.1"
description = "A terminal-style static site generator designed for writing technical blogs"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mako>=1.3.12",
    "markdown-it-py[plugins]>=4.2.0",
    "minify-html>=0.18.1",
    "pagefind[bin]>=1.5.2",
    "pydantic>=2.13.4",
    "python-frontmatter>=1.3.0",
    "python-slugify>=8.0.4",
    "sqlmodel>=0.0.38",
    "toml>=0.10.2",
]

[project.scripts]
wilton = "wilton:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
